<a name="top"></a>
<!DOCTYPE html>
<html lang="en-us">
  <head>
    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Using Rmarkdown in Hugo post - 郝鸿涛::Hongtao Hao</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,400i&display=swap" rel="stylesheet"> 
   <link href="https://fonts.googleapis.com/css?family=Noto+Serif+SC&display=swap&subset=chinese-simplified" rel="stylesheet"> 
   <link href="https://fonts.googleapis.com/css2?family=IBM+Plex+Serif&display=swap" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css2?family=PT+Serif:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet">
   <link href="https://fonts.googleapis.com/css2?family=Lato:ital,wght@0,400;0,700;1,400;1,700&display=swap" rel="stylesheet"> 
   <link href="https://fonts.googleapis.com/css2?family=Alegreya:ital,wght@0,400;0,500;0,700;1,400;1,500;1,700&display=swap" rel="stylesheet">  
   <link href="https://fonts.googleapis.com/css2?family=Open+Sans:ital,wght@0,400;0,600;1,400;1,600&display=swap" rel="stylesheet"> 

    <link rel="stylesheet" href="/css/style.css" />
    <link rel="stylesheet" href="/css/fonts.css" />
    <link href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/styles/github.min.css" rel="stylesheet">

<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/highlight.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/languages/r.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/languages/bash.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.15.10/languages/python.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/vega@5.17.0"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-lite@4.17.0"></script>
<script src="https://cdn.jsdelivr.net/npm/vega-embed@6.12.2"></script>

<script>hljs.initHighlightingOnLoad();</script>




            <link rel="icon" href="https://hongtaoh.github.io/ht10.ico">






  </head>
  
  <body>
    <div class="wrapper">
      <header class="header">
        <nav class="nav" >
      <a href="/" class="nav-logo">
        <img src="/media/ht10.png"
         width="50"
         height="50"
         alt="Hongtao Hao">
      </a>

      <ul class="nav-links" >
       
       
       <li><a href="/">Home</a></li>
       
       <li><a href="/en/en-vitae/">Vitae</a></li>
       
       <li><a href="/en/blog/">Blog</a></li>
       
       <li><a href="/en/now/">Now</a></li>
       
       <li><a href="/en/apad/">APAD</a></li>
       
       <li><a href="/cn/blog/">中文</a></li>
       
       
      </ul>
</nav>
      </header>

<main class = "content" role="main">
<div style="text-align: center">

<h1 class="article-title">Using Rmarkdown in Hugo post</h1>

<p>Hongtao Hao 
 / 2020-01-28 </p>

<hr/>
</div>

<span class="article-toolbar">

  
  
  
  
  
  
  <a href='https://github.com/hongtaoh/hongtaoh.github.io/edit/sources/content/en/blog/2020-01-28-using-markdown-in-hugo-post.Rmd'style="font-size: 24px; color: black;" target="_blank"><i class="fa fa-edit" aria-hidden="true" title="Suggest an edit of this page"></i>
  </a>
  
  
  
</span>





<div class="body-text list-text">



<div id="exercise-4.1" class="section level1">
<h1>Exercise 4.1</h1>
<pre class="r"><code>df &lt;- HairEyeColor # Changing the name of HairEyecolor
show (df) # displaying the dataframe</code></pre>
<pre><code>## , , Sex = Male
## 
##        Eye
## Hair    Brown Blue Hazel Green
##   Black    32   11    10     3
##   Brown    53   50    25    15
##   Red      10   10     7     7
##   Blond     3   30     5     8
## 
## , , Sex = Female
## 
##        Eye
## Hair    Brown Blue Hazel Green
##   Black    36    9     5     2
##   Brown    66   34    29    14
##   Red      16    7     7     7
##   Blond     4   64     5     8</code></pre>
<pre class="r"><code>e.h.freq &lt;- apply (df, c(&#39;Eye&#39;,&#39;Hair&#39;), sum) # To get a table where &#39;Eye color&#39; is the row and &#39;Hair color&#39; is the column. This line of code will sum across sex. 
e.h.prop &lt;- e.h.freq / sum (e.h.freq) # Generating joint proportions in each cell.
show (round (e.h.prop, 2)) # Round off the values in e.h.prop to the 2nd number of decimal places and then display the dataframe. </code></pre>
<pre><code>##        Hair
## Eye     Black Brown  Red Blond
##   Brown  0.11  0.20 0.04  0.01
##   Blue   0.03  0.14 0.03  0.16
##   Hazel  0.03  0.09 0.02  0.02
##   Green  0.01  0.05 0.02  0.03</code></pre>
<pre class="r"><code>h.freq &lt;- apply (df, c(&#39;Hair&#39;), sum) # This will sum across sex and eye, and display the number of people having a specific hair color. 
h.prop &lt;- h.freq / sum (h.freq) # This will display the marginal propabilities (Hair)
show ( round(h.prop,2) ) # Round off and display the dataframe.</code></pre>
<pre><code>## Black Brown   Red Blond 
##  0.18  0.48  0.12  0.21</code></pre>
<pre class="r"><code>e.freq &lt;- apply (df, c(&#39;Eye&#39;), sum) # This will sum across sex and hair, and display the number of people having a specific eye color.
e.prop &lt;- e.freq /sum (e.freq) # This will display the marginal probabilities (Eye)
show (round(e.prop, 2) ) # Round off and display the dataframe. </code></pre>
<pre><code>## Brown  Blue Hazel Green 
##  0.37  0.36  0.16  0.11</code></pre>
<pre class="r"><code>e.h.prop [&#39;Blue&#39;, ] / e.prop [&#39;Blue&#39;] # This is p(h|e=blue), i.e., the probabilities of the hair colors given that eye color is blue. </code></pre>
<pre><code>##      Black      Brown        Red      Blond 
## 0.09302326 0.39069767 0.07906977 0.43720930</code></pre>
<pre class="r"><code># To get the probabilities of hair colors given Brown eyes:
e.h.prop [&#39;Brown&#39;,] / e.prop [&#39;Brown&#39;]</code></pre>
<pre><code>##      Black      Brown        Red      Blond 
## 0.30909091 0.54090909 0.11818182 0.03181818</code></pre>
<pre class="r"><code># To get the probabilities of eye colors given Brown hair:
e.h.prop [, &#39;Brown&#39;] / h.prop [&#39;Brown&#39;]</code></pre>
<pre><code>##     Brown      Blue     Hazel     Green 
## 0.4160839 0.2937063 0.1888112 0.1013986</code></pre>
</div>
<div id="exercise-4.2" class="section level1">
<h1>Exercise 4.2</h1>
<pre class="r"><code>set.seed(47405)
N &lt;- 500
pHeads &lt;- 0.8
flipSequence &lt;- sample (x = c(0,1), prob = c(1-pHeads,pHeads), size = N, replace = T)
num.heads &lt;- cumsum (flipSequence)
num.flips &lt;- c (1:N)
prop.heads &lt;- num.heads / num.flips
plot (num.flips, prop.heads, type = &#39;o&#39;, log=&#39;x&#39;, 
      col=&quot;skyblue&quot;, xlim = c(1,N), ylim = c(0.0,1.0), cex.axis = 1.5,
      xlab = &quot;Flip Number&quot;, ylab = &quot;Proportion Heads&quot;, cex.lab = 1.5,
      main = &quot;Running Proportion of Heads&quot;, cex.main=1.5)
abline( h=pHeads, lty=&quot;dotted&quot;)
flipLetters &lt;- paste (c(&quot;T&quot;, &quot;H&quot;)[flipSequence[1:10]+1],collapse = &quot;&quot;)
displayString &lt;- paste0( &quot;Flip Sequence =&quot; , flipLetters , &quot;...&quot;)
text (N, .5, displayString, adj = c(1,0.5), cex = 1.3)
text (N, .4, paste(&quot;End Proportion = &quot;, prop.heads[N]), adj=c(1,0.5), cex=1.3)</code></pre>
<p><img src="/en/blog/2020-01-28-using-markdown-in-hugo-post_files/figure-html/unnamed-chunk-2-1.png" width="672" />
# 3</p>
<pre class="r"><code>set.seed(1)
x &lt;- seq(5, 15, length=1000)
y &lt;- dnorm(x, mean=10, sd=.20)
plot(x, y, type=&quot;l&quot;, lwd=1, col=&quot;red&quot;)</code></pre>
<p><img src="/en/blog/2020-01-28-using-markdown-in-hugo-post_files/figure-html/unnamed-chunk-3-1.png" width="672" /></p>
</div>
<div id="a" class="section level1">
<h1>3A</h1>
<pre class="r"><code>set.seed(1)
dnorm(9.9,mean=10, sd=.20)</code></pre>
<pre><code>## [1] 1.760327</code></pre>
</div>
<div id="b" class="section level1">
<h1>3B</h1>
<pre class="r"><code>set.seed(1)
# Generating a random sample of 100,000 values from the normal distribution:
heapOdata &lt;- rnorm (100000, mean = 10.0, sd = .20)
hist(heapOdata, breaks = 51, col = &quot;orange&quot;, main = &quot;rnorm&quot;) # Having a quick overview of this set of random numbers.</code></pre>
<p><img src="/en/blog/2020-01-28-using-markdown-in-hugo-post_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
</div>
<div id="c" class="section level1">
<h1>3C</h1>
<pre class="r"><code>num.between &lt;- sum( heapOdata &gt;= 9.8 &amp; heapOdata &lt; 10.0 ) # counting how many numbers fall between the interval
prob.mass &lt;- num.between / 100000 # Calculating probability mass
approx.prob &lt;- prob.mass / (10.0-9.8) # Calculating probability density (probability mass / bin width)
approx.prob </code></pre>
<pre><code>## [1] 1.69395</code></pre>
<pre class="r"><code># which is approximately the same as Part A.</code></pre>
</div>
<div id="section" class="section level1">
<h1>4</h1>
<p>According to Baye’s rule, among all joint outcomes with “negative results”, the proportion of people having the disease is <span class="math inline">\(p (user|-)\)</span>. Specifically:</p>
<p><span class="math display">\[p (user|-) = \frac{p (-|user)\cdot p(user)}{p(-)}\]</span>
We should notice that the prior, <span class="math inline">\(p(user)\)</span> is now the posterior computed from the <a href="https://www.sciencedirect.com/science/article/pii/B9780124058880000052#t0025">Table 5.4</a> in the book. Also notice that,</p>
<p><span class="math display">\[P(-) = \sum_{θ^*} \cdot P (-|θ^∗) \cdot P(θ^*)  \]</span>
Now, I will compute the posterior from <a href="https://www.sciencedirect.com/science/article/pii/B9780124058880000052#t0025">Table 5.4</a>:</p>
<p><span class="math display">\[P (user|+) = \frac {0.99 \cdot 0.001}{0.99 \cdot 0.001 + 0.05 \cdot (1-0.001)}\]</span>
Using R, we know that the result is:</p>
<pre class="r"><code>posterior &lt;- (0.99*0.001)/(0.99*0.001+0.05*(1-0.001))
posterior</code></pre>
<pre><code>## [1] 0.01943463</code></pre>
<p><span class="math display">\[
\begin{eqnarray}
P (user|-) &amp; = &amp; \frac{P (-|user)\cdot P(user)}{P(-)}\\
\\
&amp; = &amp; \frac{P (-|user)\cdot P(user)}{\sum_{θ^*} \cdot P (-|θ^∗) \cdot P(θ^*)}\\
\\
&amp; = &amp; \frac {0.01 \cdot 0.01943463 }{P(-|user) \cdot P(user) + P(-|non-user) \cdot P (non-user)} \\
\\
&amp; = &amp; \frac {0.01 \cdot 0.01943463 }{0.01 \cdot 0.01943463 + 0.95 \cdot (1-0.01943463)}
\end{eqnarray}
\]</span></p>
<p>Calculating using R:</p>
<pre class="r"><code>(0.01*posterior) / {0.01*posterior+(0.95*(1-posterior))}</code></pre>
<pre><code>## [1] 0.0002085862</code></pre>
<p>Therefore, the probability that the person has the disease given that the re-test shows “negative” is 0.0002085862.</p>
</div>
<div id="section-1" class="section level1">
<h1>5</h1>
<div id="a-1" class="section level2">
<h2>5A</h2>
<table>
<thead>
<tr class="header">
<th align="left">Test</th>
<th align="center">User</th>
<th align="center">Non-user</th>
<th align="right">Margin</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">+</td>
<td align="center">99</td>
<td align="center">4995</td>
<td align="right">5094</td>
</tr>
<tr class="even">
<td align="left">-</td>
<td align="center">1</td>
<td align="center">94905</td>
<td align="right">94906</td>
</tr>
<tr class="odd">
<td align="left">Margin</td>
<td align="center">100</td>
<td align="center">99,900</td>
<td align="right">100,000</td>
</tr>
</tbody>
</table>
</div>
<div id="b-1" class="section level2">
<h2>5B</h2>
<p>The proportion of people who have the disease given that the test result is positive:</p>
<pre class="r"><code>99/5094</code></pre>
<pre><code>## [1] 0.01943463</code></pre>
</div>
<div id="c-5d" class="section level2">
<h2>5C &amp; 5D</h2>
<pre class="r"><code>upper.left &lt;- 10000 * 0.99
upper.left</code></pre>
<pre><code>## [1] 9900</code></pre>
<pre class="r"><code>upper.right &lt;- 9990000 * 0.05
upper.right</code></pre>
<pre><code>## [1] 499500</code></pre>
<pre class="r"><code>lower.left &lt;- 10000 * 0.99 * 0.01
lower.left</code></pre>
<pre><code>## [1] 99</code></pre>
<pre class="r"><code>lower.right &lt;- 9990000 * 0.05 * 0.95
lower.right</code></pre>
<pre><code>## [1] 474525</code></pre>
<pre class="r"><code>lower.left / (lower.left+lower.right) # The result is the same as the answer to Exercise 5.1. </code></pre>
<pre><code>## [1] 0.0002085862</code></pre>
</div>
</div>


<p style="color:#777;">Last modified on 2020-11-03</p>

</div>
<a href="#top"><i class="fa fa-chevron-up" style="font-size: 30px; color: black;"></i></a>

</main>

<footer class="footer">
  



<script type="text/javascript" src="/js/math-code.js"></script>
<script async src="//mathjax.rstudio.com/latest/MathJax.js?config=TeX-MML-AM_CHTML"></script>
<script type="text/javascript" src="/js/center-img.js"></script>
  <script async src="//yihui.name/js/center-img.js"></script>

     <ul class="footer-links">
          
          <li>
            
            <a href="https://gohugo.io/" class="footer-links-kudos">Made with <img src="/media/hugo-logo.png" width="22" height="22"></a>and<a href="https://github.com/rstudio/blogdown" class="footer-links-kudos"><img src="/media/blogdown.png" width="20" height="20"></a>
          </li>
          <li>
            <a href="https://github.com/hongtaoh/hongtaoh.github.io" class="footer-links-kudos"> Content in <i class="fa fa-github" style="font-size: 18pt"></i></a>
          </li>
          <li>
            <a href = "https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en"><i class="fa fa-cc" aria-hidden="true" title="Attribution-NonCommercial-ShareAlike 4.0 International"></i> BY-NC-SA 4.0 </a>
          </li>
          
     </ul>
</footer>





